### ISSUE TITLE
No data shown in table

### ISSUE THREAD

**Issue by DipeshSt** [Collaborative-Develoment-GroupA/Backend#2]
The table on our website is not displaying data from the backend, which may have a negative effect on the user experience. Let's look into the problem by testing the data retrieval and rendering procedures, checking the API connection, and debugging the code. In order to alert users in case of any backend problems, we should also think about giving appropriate error handling.

**Comment by SimonPradhan** [comment]
The issue has been fixed and the backend is hosted online you can check the frontend, the data is now shown.
